### ISSUE TITLE
TCP/TLS streams do not work with compression enabled

### ISSUE THREAD

**Issue by lucab** [keeprocking/pygelf#5]
After some debugging time, I think I just came to the following conclusion: `compress=True` cannot work with TCP and TLS handlers, due to the GELF message structure.

In particular, I was experiencing lots of message lost in simple (non-load) test scenarios using TCP and TLS handlers. Instead, delivery was fine when switching to UDP or when disabling compression. I think that this is due to GELF using `\x00` as a message separator, and the zlib compression introducing such bytes as artifacts of the deflation.

To prevent such subtle losses in the future, I think the `GelfTcpHandler` and `GelfTlsHandler` should be changed to ignore the `compress` parameter and enforce it to `False` for all streams.

**Comment by keeprocking** [comment]
That's weird. When I was testing pygelf, everything worked - including compressed TCP and, as far as I remember, TLS handlers.
Thanks for reporting, I'll take a look as soon as possible.

**Comment by lucab** [comment]
I tried to debug this before reporting but didn't find any obvious bugs, and other implementations already experienced the issue above: https://github.com/t0xa/gelfj/pull/61.

**Comment by keeprocking** [comment]
Hey Luca, sorry for delay - got some troubles with my computer.

The fix is ready and pushed - now only UDP handler can be compressed.

Actually, compressed TCP works on short messages - it doesn't only on the long ones. But anyway, I disabled this feature for both TCP and TLS handlers.

By the way, don't hesitate to create a pull request in case you will find anything else. ;)

**Comment by lucab** [comment]
Thanks! Fixed in 855ed8cad9731b576e0cb9123c2cc0949b401d15, marking as closed.
